/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AuthProviderInterface extends ethers.utils.Interface {
  functions: {
    "authenticate(address)": FunctionFragment;
    "authenticateSub(address)": FunctionFragment;
    "controllers()": FunctionFragment;
    "deAuthenticateSub(address)": FunctionFragment;
    "hasAuthenticated(address,uint256)": FunctionFragment;
    "isAuthenticated(address)": FunctionFragment;
    "isSub(address)": FunctionFragment;
    "lastAuth(address)": FunctionFragment;
    "setControllers(address[])": FunctionFragment;
    "setTTL(uint256)": FunctionFragment;
    "subActive(address)": FunctionFragment;
    "subs(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "authenticate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "authenticateSub",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "controllers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deAuthenticateSub",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAuthenticated",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthenticated",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isSub", values: [string]): string;
  encodeFunctionData(functionFragment: "lastAuth", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setControllers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTTL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "subActive", values: [string]): string;
  encodeFunctionData(functionFragment: "subs", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "authenticate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authenticateSub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deAuthenticateSub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAuthenticated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthenticated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastAuth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTTL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subs", data: BytesLike): Result;

  events: {
    "Auth(address,uint256,address)": EventFragment;
    "AuthSub(address,address)": EventFragment;
    "AuthSubRemoved(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Auth"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuthSub"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuthSubRemoved"): EventFragment;
}

export class AuthProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AuthProviderInterface;

  functions: {
    authenticate(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "authenticate(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    authenticateSub(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "authenticateSub(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    controllers(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "controllers()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    deAuthenticateSub(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deAuthenticateSub(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isAuthenticated(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isAuthenticated(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isSub(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isSub(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    lastAuth(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "lastAuth(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setControllers(
      operators: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setControllers(address[])"(
      operators: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setTTL(
      time: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setTTL(uint256)"(
      time: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    subActive(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "subActive(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    subs(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      subAddresses: string[];
      0: string[];
    }>;

    "subs(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      subAddresses: string[];
      0: string[];
    }>;
  };

  authenticate(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "authenticate(address)"(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  authenticateSub(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "authenticateSub(address)"(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  controllers(overrides?: CallOverrides): Promise<string[]>;

  "controllers()"(overrides?: CallOverrides): Promise<string[]>;

  deAuthenticateSub(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deAuthenticateSub(address)"(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  hasAuthenticated(
    addr: string,
    latestAcceptedTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasAuthenticated(address,uint256)"(
    addr: string,
    latestAcceptedTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isAuthenticated(addr: string, overrides?: CallOverrides): Promise<boolean>;

  "isAuthenticated(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSub(addr: string, overrides?: CallOverrides): Promise<boolean>;

  "isSub(address)"(addr: string, overrides?: CallOverrides): Promise<boolean>;

  lastAuth(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  "lastAuth(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setControllers(
    operators: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setControllers(address[])"(
    operators: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setTTL(
    time: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setTTL(uint256)"(
    time: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  subActive(addr: string, overrides?: CallOverrides): Promise<boolean>;

  "subActive(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  subs(addr: string, overrides?: CallOverrides): Promise<string[]>;

  "subs(address)"(addr: string, overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    authenticate(addr: string, overrides?: CallOverrides): Promise<void>;

    "authenticate(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    authenticateSub(addr: string, overrides?: CallOverrides): Promise<void>;

    "authenticateSub(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    controllers(overrides?: CallOverrides): Promise<string[]>;

    "controllers()"(overrides?: CallOverrides): Promise<string[]>;

    deAuthenticateSub(addr: string, overrides?: CallOverrides): Promise<void>;

    "deAuthenticateSub(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAuthenticated(addr: string, overrides?: CallOverrides): Promise<boolean>;

    "isAuthenticated(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSub(addr: string, overrides?: CallOverrides): Promise<boolean>;

    "isSub(address)"(addr: string, overrides?: CallOverrides): Promise<boolean>;

    lastAuth(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "lastAuth(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setControllers(address[])"(
      operators: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTTL(time: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setTTL(uint256)"(
      time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    subActive(addr: string, overrides?: CallOverrides): Promise<boolean>;

    "subActive(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    subs(addr: string, overrides?: CallOverrides): Promise<string[]>;

    "subs(address)"(addr: string, overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {
    Auth(authenticated: null, timestamp: null, controller: null): EventFilter;

    AuthSub(subAddress: null, parentAddress: null): EventFilter;

    AuthSubRemoved(subAddress: null, parentAddress: null): EventFilter;
  };

  estimateGas: {
    authenticate(addr: string, overrides?: Overrides): Promise<BigNumber>;

    "authenticate(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    authenticateSub(addr: string, overrides?: Overrides): Promise<BigNumber>;

    "authenticateSub(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    controllers(overrides?: CallOverrides): Promise<BigNumber>;

    "controllers()"(overrides?: CallOverrides): Promise<BigNumber>;

    deAuthenticateSub(addr: string, overrides?: Overrides): Promise<BigNumber>;

    "deAuthenticateSub(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAuthenticated(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isAuthenticated(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSub(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isSub(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastAuth(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "lastAuth(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setControllers(
      operators: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setControllers(address[])"(
      operators: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    setTTL(time: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "setTTL(uint256)"(
      time: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    subActive(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "subActive(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    subs(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "subs(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authenticate(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "authenticate(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    authenticateSub(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "authenticateSub(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    controllers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "controllers()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deAuthenticateSub(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deAuthenticateSub(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAuthenticated(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAuthenticated(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSub(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isSub(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastAuth(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lastAuth(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setControllers(
      operators: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setControllers(address[])"(
      operators: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setTTL(
      time: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setTTL(uint256)"(
      time: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    subActive(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "subActive(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    subs(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "subs(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
